spring:
  data:
    mongoDb:
      uri: mongodb+srv://tdevansh793:Tomar123@cluster0.2zu7csa.mongodb.net/journalDb?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation : true

  mail:
    host: smtp.gmail.com
    port: 587
    username: tdevansh793@gmail.com
    password: ydrzimvovmuacxfl

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 8081

weather:
  api:
    key: "e6f91035d9ae6676106c1013918435e6"


logging:
  level:
    org.springframework.mail: DEBUG
    javax.mail: DEBUG


jwt:
  secret: "TaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$V"


